"""Added telegram_group_id

Revision ID: 126a9a071c4a
Revises: 4c4721f1a714
Create Date: 2024-06-07 20:04:09.011316

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "126a9a071c4a"
down_revision: Union[str, None] = "4c4721f1a714"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tournament", sa.Column("telegram_group_id", sa.Integer(), nullable=True)
    )
    op.drop_column("tournament", "next_deadline")
    op.drop_column("tournament", "end_of_next_tour")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tournament", sa.Column("end_of_next_tour", sa.DATETIME(), nullable=True)
    )
    op.add_column(
        "tournament", sa.Column("next_deadline", sa.DATETIME(), nullable=True)
    )
    op.drop_column("tournament", "telegram_group_id")
    # ### end Alembic commands ###
